This isn't how it's actually written but committing each part separately.
Have the window ID get grabbed, immediately.

Then grab the number of monitors; until I have a full grasp of the
logic and how things work, I'm just going to follow damo's lead and
keep this restricted to two monitors (oh, yeah; we're actually keeping
the two monitors capabilities. It's easier to just keep it, right now,
than rewrite with them excluded. Hopefully, we can expand this to more
than just two monitors, later).

diff --git a/aerosnap/deklanche b/aerosnap/deklanche
--- a/aerosnap/deklanche
+++ b/aerosnap/deklanche
@@ -26,6 +26,28 @@ function setPropertyString() {
 	      -set "$property_name" "$property_value"
 }
 
+function storeGeometry() {
+	window_ID="$1"
+
+
+
+
+	MON=$(xrandr -q | grep -c " connected")
+
+	case $MON in
+		1 | 2 )
+			setPropertyInteger "_MONITORS" "$MON"
+			;;
+		3 | * )
+			echo "Script cannot deal with more than 2 monitors" >&2
+
+			exit
+			;;
+	esac
+
+
+
+
 case "$1" in
 	-l|--left)
 		echo "left"
